# Generated by Django 4.1.2 on 2023-01-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-12-11'),
            preserve_default=False,
        ),
    ]
